- .github/workflows/ci.yml
- build.gradle
- config/owasp/suppressions.xml
> SDT-7: fix lombok version issue

- Jenkinsfile_CNP
- README.md
- build.gradle
- charts/civil-sdt/Chart.yaml
- charts/civil-sdt/values.aat.template.yaml
- charts/civil-sdt/values.preview.template.yaml
- charts/civil-sdt/values.yaml
- config/owasp/suppressions.xml
- docker-compose.yml
- docker/app.yml
- docker/database/Dockerfile
- docker/database/init-db.sh
- src/functionalTest/java/uk/gov/hmcts/reform/controllers/SampleFunctionalTest.java
- src/functionalTest/resources/application-functional-test.yaml
- src/integrationTest/java/uk/gov/hmcts/reform/demo/config/SwaggerPublisherTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/demo/controllers/GetWelcomeTest.java
- src/integrationTest/resources/application-integration-test.yaml
- src/main/java/uk/gov/hmcts/reform/demo/Application.java
- src/main/java/uk/gov/hmcts/reform/demo/TransactionConfiguration.java
- src/main/resources/application.yaml
- src/smokeTest/java/uk/gov/hmcts/reform/controllers/SampleSmokeTest.java
- src/smokeTest/resources/application-smoke-test.yaml
https://tools.hmcts.net/jira/browse/SDT-52
```
[ ] Yes
[ X] No
```
> SDT-52: Postgres database- Empty

- build.gradle
- lombok.config
- services/src/integ-test/java/uk/gov/moj/sdt/services/messaging/MessageWriterIntTest.java
- services/src/main/java/uk/gov/moj/sdt/services/messaging/MessageWriter.java
- services/src/main/java/uk/gov/moj/sdt/services/messaging/QueueConfig.java
- services/src/main/java/uk/gov/moj/sdt/services/messaging/asb/JsonConverter.java
- services/src/main/java/uk/gov/moj/sdt/services/messaging/asb/MessageReceiver.java
- services/src/main/java/uk/gov/moj/sdt/services/messaging/asb/MessageSender.java
- services/src/unit-test/java/uk/gov/moj/sdt/services/messaging/MessageWriterTest.java
- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/SDT-67
```
[ ] Yes
[ ] No
```
> SDT-67: Replace activemq with ASB - Unit Test

- config/owasp/suppressions.xml
N/A
Added suppressions for CVE-2022-31690, CVE-2022-31692 and CVE-2022-42252 to suppressions.xml.
```
[ ] Yes
[x] No
```
> Updated suppressions file

- build.gradle
- config/owasp/suppressions.xml
N/A
Updated tomcat version to 9.0.68 in build.gradle to address CVE-2022-42252.
Updated suppressions.xml to remove suppression for CVE-2022-42252.
```
[ ] Yes
[x] No
```
> Fix CVE-2022-42252

- config/owasp/suppressions.xml
N/A
Updated suppressions.xml to suppress CVE-2021-37533.
```
[ ] Yes
[x] No
```
> Added suppression for CVE-2021-37533

- services/src/main/java/uk/gov/moj/sdt/services/messaging/MessageWriter.java
- services/src/unit-test/java/uk/gov/moj/sdt/services/messaging/MessageWriterTest.java
https://tools.hmcts.net/jira/browse/SDT-9
```
[ ] Yes
[X ] No
```
> SDT-9: Configure ASB Deadletter reporting

- config/owasp/suppressions.xml
- consumers/src/unit-test/java/uk/gov/moj/sdt/consumers/ConsumerGatewayTest.java
- consumers/src/unit-test/java/uk/gov/moj/sdt/consumers/IndividualRequestConsumerTest.java
- consumers/src/unit-test/java/uk/gov/moj/sdt/consumers/SubmitQueryConsumerTest.java
- producers-commissioning/src/main/java/uk/gov/moj/sdt/producers/comx/services/MockBulkFeedbackService.java
- services/build.gradle
- services/src/unit-test/java/uk/gov/moj/sdt/services/BulkFeedbackServiceTest.java
- services/src/unit-test/java/uk/gov/moj/sdt/services/BulkSubmissionServiceTest.java
- services/src/unit-test/java/uk/gov/moj/sdt/services/RetryMessageAlreadySentServiceTest.java
- services/src/unit-test/java/uk/gov/moj/sdt/services/UpdateRequestServiceTest.java
- services/src/unit-test/java/uk/gov/moj/sdt/services/cache/ErrorMessagesCacheTest.java
- services/src/unit-test/java/uk/gov/moj/sdt/services/cache/GlobalParametersCacheTest.java
- services/src/unit-test/java/uk/gov/moj/sdt/services/mbeans/SdtManagementMBeanTest.java
- services/src/unit-test/java/uk/gov/moj/sdt/services/messaging/MessageWriterTest.java
- services/src/unit-test/java/uk/gov/moj/sdt/services/utils/GenericXmlParserTest.java
- services/src/unit-test/java/uk/gov/moj/sdt/services/utils/IndividualRequestsXmlParserTest.java
- transformers/src/unit-test/java/uk/gov/moj/sdt/transformers/UpdateItemTransformerTest.java
https://tools.hmcts.net/jira/browse/SDT-88
Improve Coverage for module: services
```
[ ] Yes
[*] No
```
> SDT-88 Improve Coverage for module: services

- Dockerfile
- build.gradle
- charts/civil-sdt/Chart.yaml
- config/fortify-client.properties
https://tools.hmcts.net/jira/browse/SDT-10
```
[ ] Yes
[ X] No
```
> SDT-10: Enable fortify one demand

- build.gradle
> Add toolchain config to subprojects

- charts/civil-sdt/Chart.yaml
- config/owasp/suppressions.xml
N/A
Update Java chart version to 4.0.13
```
[ ] Yes
[x] No
```
> Update Java chart version to 4.0.13

- charts/civil-sdt/Chart.yaml
N/A
Update Service Bus chart version to 0.4.0
```
[ ] Yes
[x] No
```
> Update Service Bus chart version to 0.4.0

- config/owasp/suppressions.xml
N/A
Temporarily suppress CVE-2023-20863
```
[ ] Yes
[x] No
```
> Temporarily suppress CVE-2023-20863

- charts/civil-sdt/Chart.yaml
- charts/civil-sdt/values.yaml
N/A
Added configuration to values.yaml to disable servicebus by default.  This will prevent the deploy to AAT stage from trying to create it in that environment.
```
[ ] Yes
[x] No
```
> Fix build issues in main branch

- config/owasp/suppressions.xml
N/A
Temporarily suppress CVE-2023-20862 and CVE-2023-20873.
```
[ ] Yes
[x] No
```
> Temporarily suppress CVEs

- Dockerfile
- charts/civil-sdt/values.preview.template.yaml
- lib/applicationinsights.json
N/A
- Changed applicationinsights.json connectString value to refer to alias of Application Insights connection string.
- Updated version of Application Insights to latest version.
```
[ ] Yes
[x] No
```
> Fix application insights error

- charts/civil-sdt/Chart.yaml
- charts/civil-sdt/values.preview.template.yaml
N/A
Updated servicebus chart version to 1.0.4
```
[ ] Yes
[x] No
```
> Update servicebus chart version

- config/owasp/suppressions.xml
N/A
Temporarily suppressed CVE-2023-20883
```
[ ] Yes
[x] No
```
> Temporarily suppressed CVE-2023-20883

- build.gradle
- config/owasp/suppressions.xml
N/A
Updated springboot to version 2.7.12 to fix CVE-2023-20883.
```
[ ] Yes
[x] No
```
> Fix CVE-2023-20883

- config/owasp/suppressions.xml
N/A
Temporarily suppress CVE-2023-35116
```
[ ] Yes
[x] No
```
> Temporarily suppress CVE-2023-35116

- config/owasp/suppressions.xml
- dao/src/main/java/uk/gov/moj/sdt/interceptors/service/PersistServiceRequestImpl.java
N/A
Temporarily suppress CVE-2023-2976
```
[ ] Yes
[x] No
```
> Temporarily suppress CVE-2023-2976

- config/owasp/suppressions.xml
N/A
Temporarily suppress CVE-2023-34462
```
[ ] Yes
[x] No
```
> Temporarily suppress CVE-2023-34462

- docker-compose.yml
N/A
Added commented out remote JVM debug settings to docker-compose.yml.  These can be uncommented to allow local debugging of SDT.
```
[ ] Yes
[x] No
```
> Add JVM debug settings

- config/owasp/suppressions.xml
N/A
Temporarily suppress CVE-2023-34034
```
[ ] Yes
[x] No
```
> Temporarily suppress CVE-2023-34034

- build.gradle
- config/owasp/suppressions.xml
SDT-143 (https://tools.hmcts.net/jira/browse/SDT-143)
Updated build.gradle:
- Changed version of guava from 30.0 to 32.0.1.
Removed CVE-2023-2976 from suppressions.xml.
```
[ ] Yes
[x] No
```
> Fix CVE-2023-2976

- charts/civil-sdt/values.yaml
SDT-145 (https://tools.hmcts.net/jira/browse/SDT-145)
Set IDAM_API_URL and IDAM_S2S_URL environment variables in values.yaml.
```
[ ] Yes
[x] No
```
> SDT-145: Set IDAM URL environment variables

- charts/civil-sdt/Chart.yaml
- charts/civil-sdt/values.yaml
SDT-145 (https://tools.hmcts.net/jira/browse/SDT-145)
Added references to SDT IDAM user secrets to values.yaml.
```
[ ] Yes
[X] No
```
> SDT-145: Set SDT IDAM user details from secrets

- charts/civil-sdt/Chart.yaml
- charts/civil-sdt/values.yaml
- src/main/resources/application.yaml
SDT-145 (https://tools.hmcts.net/jira/browse/SDT-145)
- Added civil-sdt-idam-client-secret secret to values.yaml.
- Added IDAM client properties to application.yaml.
- Updated chart version number.
```
[ ] Yes
[x] No
```
> SDT-145: Add IDAM client settings

- config/owasp/suppressions.xml
N/A
Temporarily suppressed CVE-2023-41080
```
[ ] Yes
[x] No
```
> Temporarily suppressed CVE-2023-41080

- .github/renovate.json
SDT-160 (https://tools.hmcts.net/jira/browse/SDT-160)
Updated configuration in renovate.json to that required by organisation. Chose to use automerge-minor preset.
```
[ ] Yes
[x] No
```
> SDT-160: Update renovate configuration

- build.gradle
- config/owasp/suppressions.xml
N/A
Updated tomcatVersion property in main build.gradle file to 9.0.80 and removed suppression of CVE-2023-41080 from suppressions.xml.  This builds on changes made by renovate in #215 which missed updating the tomcatVersion property.
```
[ ] Yes
[x] No
```
> Fix CVE-2023-41080

- config/owasp/suppressions.xml
N/A
Temporarily suppress CVE-2023-36479, CVE-2023-40167 and CVE-2023-41900.
```
[ ] Yes
[x] No
```
> Temporarily suppress jetty CVEs

- Dockerfile
N/A
Added configuration to Dockerfile to manage Application Insights with Renovate.
```
[ ] Yes
[x] No
```
> Manage app insights with renovate

- build.gradle
> SDT-166: SDT common version updated to 1.1.0

- .github/dependabot.yml
SDT-165 (https://tools.hmcts.net/jira/browse/SDT-165)
Deleted dependabot config file. 
```
[ ] Yes
[x] No
```
> SDT-165 - Deleted dependabot config file

- config/owasp/suppressions.xml
N/A
Temporarily suppress CVE-2023-4586
```
[ ] Yes
[x] No
```
> Temporarily suppress CVE-2023-4586

- Jenkinsfile_CNP
> SDT-157: stop demo branch to sync

- config/owasp/suppressions.xml
N/A
Temporarily suppress CVE-2023-36414 and CVE-2023-36415
```
[ ] Yes
[x] No
```
> Temporarily suppress CVE-2023-36414 and CVE-2023-36415

- config/owasp/suppressions.xml
SDT-177 (https://tools.hmcts.net/jira/browse/SDT-177)
Removed redundant suppressions from suppressions.xml.  These appear to have been addressed by dependency updates carried out by Renovate.
```
[ ] Yes
[x] No
```
> SDT-177: Remove redundant suppressions

- config/owasp/suppressions.xml
N/A
Suppressed CVE-2023-4586 again.  Was showing as resolved, but details of vulnerability were updated on 23/10/2023 and it is now being flagged again.
```
[ ] Yes
[x] No
```
> Temporarily suppressed CVE-2023-4586

- build.gradle
- consumers/src/unit-test/java/uk/gov/moj/sdt/consumers/SubmitQueryConsumerTest.java
N/A
- Removed duplicate and redundant dependencies from build.gradle.
- Removed unused imports from SubmitQueryConsumerTest.
- Renamed mockClient local variable in SubmitQueryConsumerTest.testGetClientImpl to avoid hiding a class field of the same name.
```
[ ] Yes
[x] No
```
> Removed duplicate and redundant dependencies

- infrastructure/perftest.tfvars
SDT-124 (https://tools.hmcts.net/jira/browse/SDT-124)
Temporarily changed perftest service bus tier to premium
```
[ ] Yes
[x] No
```
> Change perftest service bus tier

- services/src/integ-test/java/uk/gov/moj/sdt/services/config/ServicesTestConfig.java
- services/src/main/java/uk/gov/moj/sdt/services/BulkSubmissionService.java
- services/src/main/java/uk/gov/moj/sdt/services/messaging/MessageWriter.java
- services/src/main/java/uk/gov/moj/sdt/services/utils/MessagingUtility.java
- services/src/unit-test/java/uk/gov/moj/sdt/services/messaging/MessageWriterTest.java
- services/src/unit-test/java/uk/gov/moj/sdt/services/utils/MessagingUtilityTest.java
> Perftest issue: introduce ExecutorService to run queue immediately

- services/src/main/java/uk/gov/moj/sdt/services/TargetApplicationSubmissionService.java
- services/src/main/java/uk/gov/moj/sdt/services/messaging/MessageWriter.java
- services/src/main/java/uk/gov/moj/sdt/services/utils/MessagingUtility.java
- services/src/unit-test/java/uk/gov/moj/sdt/services/utils/MessagingUtilityTest.java
> Perftest issue: Fix issue messages not being sent to service bus queue

- scripts/legacy-db-migration/README.md
- scripts/legacy-db-migration/export/export_bulk_customer_applications.sql
- scripts/legacy-db-migration/export/export_bulk_customers.sql
- scripts/legacy-db-migration/export/export_bulk_submissions.sql
- scripts/legacy-db-migration/export/export_error_logs.sql
- scripts/legacy-db-migration/export/export_individual_requests.sql
- scripts/legacy-db-migration/export/export_service_requests.sql
- scripts/legacy-db-migration/import/import.sql
- scripts/legacy-db-migration/import/reset_sequences.sql
- scripts/legacy-db-migration/validation/data_migration_validation.sql
- scripts/legacy-db-migration/validation/data_migration_validation_oracle.sql
SDT-170 (https://tools.hmcts.net/jira/browse/SDT-170)
Added scripts to be used to migrate data from legacy SDT Oracle database to new Postgres database.  These are being added for reference only.
```
[ ] Yes
[x] No
```
> SDT-170: Database migration scripts

- config/owasp/suppressions.xml
N/A
Suppressing CVE-2023-36052 
```
[ ] Yes
[x] No
```
> CVE-2023-36052 Suppression

- config/owasp/suppressions.xml
N/A
Suppressing CVE-2023-6378
```
[ ] Yes
[x] No
```
> CVE-2023-6378 Suppression

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/SDT-182
Set logback.version to 1.2.13.
Removing the CVE-2023-6378 Temporary Suppression 
```
[ ] Yes
[x] No
```
> Fix CVE-2023-6378

- config/owasp/suppressions.xml
> Remove suppression for CVE-2023-4586

- infrastructure/key-vault.tf
SDT-208 (https://tools.hmcts.net/jira/browse/SDT-208)
Added infrastructure code to set up production key vault access for DTS Production DB Reporting principle.  This is needed for the AM dashboard daily updates Azure pipeline.
```
[ ] Yes
[x] No
```
> SDT-208: Key vault access for AM dashboard pipeline

- dao/src/main/java/uk/gov/moj/sdt/dao/GenericDao.java
- services/src/main/java/uk/gov/moj/sdt/services/AbstractSdtService.java
N/A
Add debug logging
```
[ ] Yes
[x] No
```
> Add debug logging

- charts/civil-sdt/Chart.yaml
- charts/civil-sdt/values.yaml
Set Pricing Tier default to Premium
```
[x] Yes
[ ] No
```
> Set Pricing Tier default to Premium

- charts/civil-sdt/Chart.yaml
- charts/civil-sdt/values.yaml
> Revert "Set Pricing Tier default to Premium"

- infrastructure/service-bus.tf
> Remove pricing tier from TF

- src/main/java/uk/gov/moj/sdt/Application.java
SDT-227 (https://tools.hmcts.net/jira/browse/SDT-227)
Added PostConstruct annotated method to Application.java to explicitly set the timezone to Europe/London.
```
[ ] Yes
[x] No
```
> SDT-227: Set timezone to Europe/London

- infrastructure/aat.tfvars
- infrastructure/service-bus.tf
- infrastructure/variables.tf
Also requires upgrading to Premium
```
[ ] Yes
[ ] No
```
> Increase AAT max queue size

- build.gradle
SDT-230 (https://tools.hmcts.net/jira/browse/SDT-230)
Updated version of SDT common to 3.2.1.  This contains a change to set the updated date on an individual request when it is created.
```
[ ] Yes
[x] No
```
> SDT-230: Update version of SDT common to 3.2.1

- services/src/main/java/uk/gov/moj/sdt/services/utils/MessagingUtility.java
N/A
Add debug logging to MessagingUtility
```
[ ] Yes
[x] No
```
> Add debug logging to MessagingUtility

- services/src/main/java/uk/gov/moj/sdt/services/messaging/MessageWriter.java
N/A
Add debug logging to MessageWriter
```
[ ] Yes
[x] No
```
> Add debug logging to MessageWriter

- services/src/main/java/uk/gov/moj/sdt/services/utils/MessagingUtility.java
- src/main/resources/application.yaml
N/A
Add executor service to single request enqueueRequest method
```
[ ] Yes
[x] No
```
> Add executor service to single request enqueueRequest method

- services/src/main/java/uk/gov/moj/sdt/services/utils/MessagingUtility.java
N/A
Add additional logging to MessagingUtility
```
[ ] Yes
[x] No
```
> Add additional logging to MessagingUtility

- services/src/main/java/uk/gov/moj/sdt/services/utils/MessagingUtility.java
N/A
Remove additional logging from MessagingUtility
```
[ ] Yes
[x] No
```
> Remove additional logging from MessagingUtility

- build.gradle
SDT-233 (https://tools.hmcts.net/jira/browse/SDT-233)
Added declaration of repositories to allprojects part of build.gradle
```
[ ] Yes
[x] No
```
> SDT-233: Add declaration of repositories

- build.gradle
SDT-199 (https://tools.hmcts.net/jira/browse/SDT-199)
Updated sdt-common version to 3.2.1-phase-3.0.6.  This contains the changes for SDT-199.
```
[ ] Yes
[x] No
```
> SDT-199: Increase number of particulars lines

- infrastructure/aat.tfvars
[DTSCCI-1193](https://tools.hmcts.net/jira/browse/DTSCCI-1193)
Change SKU setting to Standard from Premium for Civil service bus messaging
> DTSCCI-1993: Change SKU setting to Standard from Premium

- config/owasp/suppressions.xml
N/A
Added the following CVE to the temporary suppression list: CVE-2024-6763, CVE-2024-22201, CVE-2024-8184, CVE-2024-38820, CVE-2025-25193
```
[ ] Yes
[x] No
```
> Suppress new CVEs

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/SDT-250
Removed CVE-2023-36052 from suppressions.xml as this has been remediated and no longer causes a build failure in the pipeline.
```
[ ] Yes
[x] No
```
> Removed CVE-2023-36052 from suppressions.xml

- build.gradle
N/A
Revert ben-manes.versions to v0.51.0
Reverted junit5 monorepo to x.11.4
Reverted azure-core to version 1.54.1'
Reverted azure-messaging-servicebus to version: 7.15.2
Reverted spring-cloud-azure-starter-servicebus-jms to version: 4.19.0
Reverted junit:junit-bom to 5.11.4
```
[ ] Yes
[x] No
```
> Revert 3 renovate changes that caused the build to fail

- config/owasp/suppressions.xml
N/A
added CVE-2023-1932 to  suppressions.xml
```
[ ] Yes
[x] No
```
> Suppress CVE 2023 1932

- infrastructure/database.tf
https://tools.hmcts.net/jira/browse/SDT-256
SDT-256 - Update DB infrastructure to enable reporting on tables used by AM dashboard.
```
[ ] Yes
[x] No
```
> SDT-256 Enable reporting on DB infrastructure for AMDB.

- config/owasp/suppressions.xml
N/A
Added CVE-2024-47535 and CVE-2025-24970 to suppressions.xml
```
[ ] Yes
[x] No
```
> Added CVE-2024-47535 and CVE-2025-24970 to suppressions.xml
