build.gradle, config/owasp/suppressions.xml
N/A
Updated postgresql version to 42.5.1 in build.gradle to resolve CVE-2022-41946.  Took opportunity to replace hardcoded postgresql versions with reference to postgresqlVersion variable and remove duplicate/redundant org.postgresql and org.testcontainers testImplementation references.
Also removed postgresl.version ext declaration as dependency tree showed that the version it referenced wasn't being used.
Updated suppressions.xml to remove suppression for CVE-2022-41946.
```
[ ] Yes
[x] No
```
=> Fix CVE-2022-41946

build.gradle, config/owasp/suppressions.xml, producers-api/src/unit-test/resources/xml/validation/BulkRequestResponse/BulkSubmitRequestMandatoryMissingErrorMessages.txt, producers-api/src/unit-test/resources/xml/validation/SubmitQueryRequestResponse/SubmitQueryRequestMandatoryMissingErrorMessages.txt
SDT-25 (https://tools.hmcts.net/jira/browse/SDT-25)
A bug in the openJDK implementation of xerces 2.12.2 causes cvc-complex-type.4 errors to be reported twice.  This causes two of the XSD validation unit tests to fail when using openJDK 11.0.17 or above.  To fix this added a dependency for the actual version of xerces 2.12.2 which doesn't have the bug in it.
Removed duplicate cvc-complex-type.4 errors from BulkSubmitRequestMandatoryMissingErrorMessages.txt and SubmitQueryRequestMandatoryMissingErrorMessages.txt.
Added suppression for CVE-2022-1471 which is flagged by Template CI dependency check stage.
```
[ ] Yes
[x] No
```
=> SDT-25: Fix XSD validation unit tests

build.gradle, config/owasp/suppressions.xml
N/A
Updated spring-security version in build.gradle to 5.7.5 to fix CVE-2022-31690 and CVE-2022-31692.  Removed corresponding suppressions from suppressions.xml.
```
[ ] Yes
[x] No
```
=> Fix CVE-2022-31690 and CVE-2022-31692

build.gradle
N/A
Changed values of sonar.projectName and sonar.projectKey properties in build.gradle to reference civil-sdt rather than civil-sdt-gateway.  This should ensure that the civil-sdt sonar reports are associated with the correct project in sonarcloud.
```
[ ] Yes
[x] No
```
=> Corrected sonar project properties

build.gradle, config/owasp/suppressions.xml, utils/src/unit-test/java/uk/gov/moj/sdt/utils/AbstractSdtXmlTestBase.java, validators/src/main/java/uk/gov/moj/sdt/validators/XmlValidator.java
SDT-25 (https://tools.hmcts.net/jira/browse/SDT-25)
Explicitly set class that implements SaxParserFactory to the xercesImpl SaxParserFactoryImpl class.  This should ensure that xerces implementation is always used over default Java implementation.
Updated suppressions.xml to suppress CVE-2017-10355.
```
[ ] Yes
[x] No
```
=> SDT-25: Ensure xercesImpl is used

charts/civil-sdt/Chart.yaml
N/A/
Updated Helm java chart version to 4.0.9. This is required as older versions aren't supported in latest AKS release (1.25).
```
[ ] Yes
[x] No
```
=> Update Helm java chart version to 4.0.9

build.gradle, config/owasp/suppressions.xml
N/A
Updated DependencyCheck version to 8.0.2.  This is needed to fit in with a change to be made to the common pipeline to utilise the global suppressions file (see https://jeremylong.github.io/DependencyCheck/suppressions/publishedSuppressions.xml).
In addition, updated versions plugin to latest version (0.44.0) and removed duplicate suppressions from suppressions.xml.
```
[ ] Yes
[x] No
```
=> Updated DependencyCheck version to 8.0.2

config/owasp/suppressions.xml
N/A
Added CVE-2022-40705 to false positives section of suppressions.xml.  This can be removed when Dependency Check has been updated (see https://github.com/jeremylong/DependencyCheck/issues/5543).
```
[ ] Yes
[x] No
```
=> Suppress CVE-2022-40705 as a false positive

Jenkinsfile_nightly, consumers/src/unit-test/java/uk/gov/moj/sdt/consumers/IndividualRequestConsumerTest.java
N/A
Changed IndividualRequestConsumerTest.processIndividualRequestOutageReattemptLoop() to check for at least 2 invocations of mockClient.submitIndividual() rather than an exact number.
Changed Jenkinsfile_nightly so that Fortify scan is invoked using "afterAlways" instead of deprecated "after".
```
[ ] Yes
[x] No
```
=> Fix build failures

infrastructure/variables.tf
N/A
Remove redundant deployment_namespace Terraform var from variables.tf
```
[ ] Yes
[x] No
```
=> Remove redundant deployment_namespace Terraform var

infrastructure/key-vault.tf, infrastructure/main.tf, infrastructure/output.tf, infrastructure/service-bus.tf, infrastructure/state.tf
N/A
- Removed civil-shared resource declaration from main.tf.  This is already being created in the civil-shared-infrastructure Terraform configuration.  Replaced it with a new local civil_shared_resource_group variable.
- Replaced references to shared resource group with civil_shared_resource_group variable in key-vault.tf and service-bus.tf.
- Moved output variables from key-vault.tf and service-bus.tf to output.tf.
```
[ ] Yes
[x] No
```
=> Updated Terraform configuration

Jenkinsfile_nightly
N/A
Changed the schedule so that nightly builds only run during the week.  Typically no development will be taking place over a weekend so little benefit in having the nightly builds run then.
```
[ ] Yes
[x] No
```
=> Stop nightly builds running at weekends

infrastructure/key-vault.tf, infrastructure/main.tf
N/A
Added configuration to main.tf and key-vault.tf files to create an SDT key vault.  This will be used in place of the civil key vault which is owned by the civil-service repository.
```
[ ] Yes
[x] No
```
=> Add SDT key vault

.gitignore, Dockerfile, build.gradle, charts/civil-sdt/Chart.yaml, charts/civil-sdt/values.preview.template.yaml, charts/civil-sdt/values.yaml, infrastructure/app-insights.tf, lib/applicationinsights.json, src/main/resources/application.yaml
N/A
Configured civil-sdt for use with Application Insights v3.  This is based on the changes made in the example https://github.com/hmcts/draft-store/pull/989 pull request.
```
[ ] Yes
[x] No
```
=> Configure project to use Application Insights v3

lib/applicationinsights.json
N/A
As recommended by PlatOps, configured AppInsights to only sample 1% of health requests.  This will be enough to show any errors and will prevent logs from being swamped with them.
```
[ ] Yes
[x] No
```
=> Reduce AppInsights health sampling rate

services/src/main/java/uk/gov/moj/sdt/services/messaging/MessageWriter.java, services/src/unit-test/java/uk/gov/moj/sdt/services/messaging/MessageWriterTest.java
SDT-135 (https://tools.hmcts.net/jira/browse/SDT-135)
- Changed MessageWriter.queueMessage() to reset connection and queue message again if connection has timed out due to idle period expiring.
- Added tests for new functionality to MessageWriterTest class.
- Tidied up existing tests in MessageWriterTest class: Reduced repeated code and improved test coverage.
```
[ ] Yes
[x] No
```
=> SDT-135: Reset queue connection after idle timeout

config/owasp/suppressions.xml
SDT-143 (https://tools.hmcts.net/jira/browse/SDT-143)
Moved CVE-2023-35116 to false positives section of suppressions.xml.  It's not believed to be a valid vulnerability and requests have been made to remove it from the NIST database.
```
[ ] Yes
[x] No
```
=> Moved CVE-2023-35116 to false positives section

build.gradle, config/owasp/suppressions.xml
N/A
Updated azure-messaging-servicebus dependency to version 7.14.3.  This version does not have a dependency on the libraries affected by CVE-2023-39533.
```
[ ] Yes
[x] No
```
=> Fix CVE-2023-39533

build.gradle
N/A
- Changed tomcat dependencySets to use tomcatVersion property.
- Removed duplicate org.springdoc:springdoc-openapi-ui dependency
- Removed resolution strategy for springframework version.  This isn't needed following update to spring boot version.
```
[ ] Yes
[x] No
```
=> Tidy up build.gradle

config/pmd/ruleset.xml
N/A
The BeanMembersShouldSerialize rule has been deprecated since PMD version 6.52.0. It has been replaced with NonSerializableClass (see https://docs.pmd-code.org/pmd-doc-6.55.0/pmd_rules_java_errorprone.html#beanmembersshouldserialize). Changed exclusion for BeanMembersShouldSerialize in PMD ruleset.xml to NonSerializableClass.
The change will prevent "Unable to exclude rules [BeanMembersShouldSerialize] from ruleset reference category/java/errorprone.xml; perhaps the rule name is misspelled or the rule doesn't exist anymore?" messages being displayed in the build output.
```
[ ] Yes
[x] No
```
=> Replace deprecated BeanMembersShouldSerialize PMD rule

build.gradle, charts/civil-sdt/Chart.yaml, charts/civil-sdt/values.yaml, config/owasp/suppressions.xml, infrastructure/service-bus.tf, src/main/resources/application.yaml
SDT-178 (https://tools.hmcts.net/jira/browse/SDT-178)
- Added spring-cloud-azure-starter-servicebus-jms depedency to build.gradle.  This replaces azure-servicebus-jms-spring-boot-starter.  Also added a constraint which should resolve CVE-2023-36414 and CVE-2023-36415, but these are still being flagged by DependencyCheck.  Added suppressions back to suppressions.xml until this is sorted out.
- Removed activemq-broker and activemq-client dependencies from build.gradle.  These are automatically included by spring-boot-starter-activemq.  Replaced activeMQVersion property with spring boot activemq.version property to set ActiveMQ version.
- Changed spring-boot-starter-activemq dependency to a test dependency and moved it to test dependency section.
- Removed duplicate …
=> SDT-178: Ensure SDT uses servicebus

infrastructure/app-insights.tf
https://tools.hmcts.net/jira/browse/DTSPO-15909
Updating azurerm_application_insights resource and replacing it with module terraform-module-application-insights
This will allow us to migrate Classic Application Insights using https://github.com/hmcts/app-insights-migration-tool as Classic Application Insights will deprecated and will be retired in February 2024.
=> DTSPO-15909 - migrated Application Insights

build.gradle
https://tools.hmcts.net/jira/browse/SDT-193
The log4j-to-slf4j exclusions are no longer needed following the removal of the log4j-core dependency
```
[ ] Yes
[x] No
```
=> Remove log4j-to-slf4j exclusions from civil-sdt build.gradle

build.gradle, consumers/src/main/java/uk/gov/moj/sdt/cmc/consumers/CMCConsumerGateway.java, consumers/src/main/java/uk/gov/moj/sdt/cmc/consumers/config/CMCConfig.java, consumers/src/main/java/uk/gov/moj/sdt/cmc/consumers/decoder/CMCErrorDecoder.java, consumers/src/main/java/uk/gov/moj/sdt/cmc/consumers/exception/CMCCaseLockedException.java, consumers/src/unit-test/java/uk/gov/moj/sdt/cmc/consumers/CMCConsumerGatewayTest.java, consumers/src/unit-test/java/uk/gov/moj/sdt/cmc/consumers/decoder/CMCErrorDecoderTest.java, dao/src/integ-test/resources/application-integ.yaml, dao/src/main/java/uk/gov/moj/sdt/dao/IndividualRequestDao.java, services/src/integ-test/resources/application-integ.yaml, services/src/main/java/uk/gov/moj/sdt/services/RetryCaseLockedService.java, services/src/main/java/uk/gov/moj/sdt/services/utils/RetryCaseLockedUtility.java, services/src/unit-test/java/uk/gov/moj/sdt/services/RetryCaseLockedServiceTest.java, services/src/unit-test/java/uk/gov/moj/sdt/services/utils/RetryCaseLockedUtilityTest.java, src/main/resources/application.yaml
SDT-200 (https://tools.hmcts.net/jira/browse/SDT-200)
Added CMCCaseLockedException class.
Added CMCErrorDecoder class to translate error responses from CMC to specific exception types.
Updated CMCConfig to create CMCErrorDecoder bean.
Updated CMCConsumerGateway to handle CMCCaseLockedExceptions.
Added RetryCaseLockedService and RetryCaseLockedUtility classes.  These implement the process to retry individual requests that have received a case locked notification after a configurable period of time has elapsed.
Added method to IndividualRequestDao to get individual requests that have been in case locked state for more than a specified period of time.
Updated application.yaml with parameters for RetryCaseLockedService.
Added unit test classes for new classes.
**Does this PR introduce a …
=> SDT-200: Handle Case Locked notifications from CMC

build.gradle, consumers/src/main/java/uk/gov/moj/sdt/cmc/consumers/CMCConsumerGateway.java, consumers/src/main/java/uk/gov/moj/sdt/cmc/consumers/decoder/CMCErrorDecoder.java, consumers/src/main/java/uk/gov/moj/sdt/cmc/consumers/exception/CMCRejectedException.java, consumers/src/main/java/uk/gov/moj/sdt/cmc/consumers/response/ErrorResponse.java, consumers/src/unit-test/java/uk/gov/moj/sdt/cmc/consumers/CMCConsumerGatewayTest.java, consumers/src/unit-test/java/uk/gov/moj/sdt/cmc/consumers/decoder/CMCErrorDecoderTest.java, consumers/src/unit-test/java/uk/gov/moj/sdt/cmc/consumers/response/ErrorResponseTest.java, services/src/main/java/uk/gov/moj/sdt/services/AbstractSdtService.java, services/src/main/java/uk/gov/moj/sdt/services/TargetApplicationSubmissionService.java, services/src/unit-test/java/uk/gov/moj/sdt/services/TargetApplicationSubmissionServiceTest.java
SDT-203 (https://tools.hmcts.net/jira/browse/SDT-203)
- Added ErrorResponse class for converting body of bad request errors received from CMC.
- Added CMCRejectedException class.
- Updated CMCErrorDecoder to catch bad request errors and convert them to CMCRejectedExceptions via ErrorResponse objects.  If error has an unexpected body then a CMCException is raised instead.
- Updated CMCConsumerGateway to catch and handle CMCRejectedExceptions.  Removed case offline error handling code from exception catch block as this is now a CMCRejectedException.
- Updated CMCConsumerGateway to add a catch block to rethrow CMCExceptions returned by CMCErrorDecoder.
- Updated CMCConsumerGateway RetryableException catch block to throw a CMCException for non-timeout exceptions.
- Updated …
=> SDT-203: Handle CMC errors

infrastructure/app-insights.tf, infrastructure/service-bus.tf, infrastructure/state.tf
SDT-236 (https://tools.hmcts.net/jira/browse/SDT-236)
state.tf
- Changed azurerm skip_provider_registration argument to resource_provider_registrations.  This is to resolve a deprecation warning.
- Changed azurerm required_providers version to "~> 4.0"
app-insights.tf
- Changed application_insights module to reference 4.x branch of terraform-module-application-insights
service-bus.tf
- Changed servicebus-namespace module to reference 4.x branch of terraform-module-servicebus-namespace
- Changed servicebus-sdt-queue module to reference 4.x branch of terraform-module-servicebus-queue
- Removed zone_redundant argument from servicebus-namespace module.  Argument was marked as deprecated in azurerm version 3 and has been removed in azurerm version 4.
**Does this PR introduce a breaking …
=> SDT-236: Update azurerm to version 4 (demo)

infrastructure/app-insights.tf, infrastructure/service-bus.tf, infrastructure/state.tf
SDT-236 (https://tools.hmcts.net/jira/browse/SDT-236)
state.tf
- Changed azurerm skip_provider_registration argument to resource_provider_registrations.  This is to resolve a deprecation warning.
- Changed azurerm required_providers version to "~> 4.0"
app-insights.tf
- Changed application_insights module to reference 4.x branch of terraform-module-application-insights
service-bus.tf
- Changed servicebus-namespace module to reference 4.x branch of terraform-module-servicebus-namespace
- Removed zone_redundant argument from servicebus-namespace module.  Argument was marked as deprecated in azurerm version 3 and has been removed in azurerm version 4.
- Changed servicebus-sdt-queue module to reference 4.x branch of terraform-module-servicebus-queue
**Does this PR introduce a breaking …
=> SDT-236: Update azurerm to version 4
